#!/bin/bash

# Copyright (c) 2016, Metasystems Technologies Inc (MTI), Nicholas Van Wyen
# All rights reserved.
# 
# Redistribution and use in source and binary forms, with or without 
# modification, are permitted provided that the following conditions are met:
# 
# 1. Redistributions of source code must retain the above copyright notice, this
#    list of conditions and the following disclaimer.
# 
# 2. Redistributions in binary form must reproduce the above copyright notice,
#    this list of conditions and the following disclaimer in the documentation
#    and/or other materials provided with the distribution.
# 
# 3. Neither the name of the copyright holder nor the names of its contributors
#    may be used to endorse or promote products derived from this software
#    without specific prior written permission.
# 
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
# ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
# WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
# SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
# CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
# OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

cat=`which cat`
sed=`which sed`
head=`which head`
date=`which date`

if [[ -z ${cat} ]] ; then

    echo "cat utility not found!"
    exit 2

else

    if [ ! -f ${cat} ] ; then

        echo "cat [${cat}] invalid"
        exit 2

    fi

fi

if [[ -z ${sed} ]] ; then

    echo "sed utility not found!"
    exit 2

else

    if [ ! -f ${sed} ] ; then

        echo "sed [${sed}] invalid"
        exit 2

    fi

fi

if [[ -z ${head} ]] ; then

    echo "head utility not found!"
    exit 2

else

    if [ ! -f ${head} ] ; then

        echo "head [${head}] invalid"
        exit 2

    fi

fi

if [[ -z ${date} ]] ; then

    echo "date utility not found!"
    exit 2

else

    if [ ! -f ${date} ] ; then

        echo "date [${date}] invalid"
        exit 2

    fi

fi

if [ -f hive.par.sql.in ] ; then

    if [ -f ../VERSION ] ; then

        ver=`${cat} ../VERSION | ${head} -n 1`

        if [[ ! -z {ver} ]] ; then

            if [ -f hive.par.sql ] ; then

                dts=`${date} +%Y%m%d%H%M%S`
                echo -n "Found previous hive.par.sql, backing up to hive.par.sql.${dts} ... "
                cp hive.par.sql hive.par.sql.${dts}
                echo

            fi

            echo -n "Setting version data ${ver} ... "
            ${sed} s/%version%/${ver}/g hive.par.sql.in > hive.par.sql

            if [ "$?" -eq 0 ] ; then

                echo "ok"

            else

                echo "failed"
                exit 1

            fi

        else

            echo "No version data avaiable!"
            exit 2

        fi

    else

        echo "Hive ODCI VERSION file not found!"
        exit 2

    fi

else

    echo "Hive ODCI Parameter IN file not found!"
    exit 2

fi

exit 0
