#!/bin/bash

# Copyright (c) 2017, Metasystems Technologies Inc.
# Nicholas Van Wyen
#
# This library is free software; you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public
# License as published by the Free Software Foundation; either
# version 3 of the License, or (at your option) any later version.
# See the file COPYING included with this distribution for more
# information.

#
cat=`which cat`
sed=`which sed`
head=`which head`
date=`which date`

dir=$(dirname $0)
inf="hive.par.sql.in"
out="hive.par.sql"
tag="%version%"

if [[ -z ${cat} ]] ; then

    echo "cat utility not found!"
    exit 2

else

    if [ ! -f ${cat} ] ; then

        echo "cat [${cat}] invalid"
        exit 2

    fi

fi

if [[ -z ${sed} ]] ; then

    echo "sed utility not found!"
    exit 2

else

    if [ ! -f ${sed} ] ; then

        echo "sed [${sed}] invalid"
        exit 2

    fi

fi

if [[ -z ${head} ]] ; then

    echo "head utility not found!"
    exit 2

else

    if [ ! -f ${head} ] ; then

        echo "head [${head}] invalid"
        exit 2

    fi

fi

if [[ -z ${date} ]] ; then

    echo "date utility not found!"
    exit 2

else

    if [ ! -f ${date} ] ; then

        echo "date [${date}] invalid"
        exit 2

    fi

fi

if [ -f ${dir}/${inf} ] ; then

    if [ -f ${dir}/../VERSION ] ; then

        ver=`${cat} ${dir}/../VERSION | ${head} -n 1`

        if [[ ! -z ${ver} ]] ; then

            echo -n "Setting version data ${ver} ... "
            ${sed} s/${tag}/${ver}/g ${dir}/${inf} > ${dir}/${out}

            if [ "$?" -eq 0 ] ; then

                echo "ok"

            else

                echo "failed"
                exit 1

            fi

        else

            echo "No version data avaiable!"
            exit 2

        fi

    else

        echo "Xcp VERSION file not found!"
        exit 2

    fi

else

    echo "Version Parameter IN file not found!"
    exit 2

fi

exit 0
